apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cardano-smart
  name: deployment-restart-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-deployment-binding
  namespace: cardano-smart
subjects:
- kind: ServiceAccount
  name: deployment-restart-sa
  namespace: cardano-smart
roleRef:
  kind: Role
  name: deployment-restart-role
  apiGroup: rbac.authorization.k8s.io
