apiVersion: v1
kind: Service
metadata:
  name: private-gpt-service
  namespace: cardano-smart
spec:
  selector:
    app: private-gpt
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8080
  type: NodePort
