apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama-1
        image: ollama/ollama:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1800m"
            memory: "15Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "1800m"
            memory: "15Gi"
            nvidia.com/gpu: 1
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
        cloud.google.com/compute-class: Accelerator
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: ollama-pvc
