apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama-1
        image: ollama/ollama:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1250m"
            ephemeral-storage: "10Gi"
            memory: "20Gi"
            nvidia.com/gpu: 1
          requests:
            cpu: "600m"
            ephemeral-storage: "4Gi"
            memory: "9Gi"
            nvidia.com/gpu: 1
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access
          readOnly: true
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
        cloud.google.com/gke-accelerator-count: "1"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: kube-api-access
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
