apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cardano-smart
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 31080
  type: NodePort
