apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /cardano_smart
    server: 10.26.148.162
  persistentVolumeReclaimPolicy: Retain