apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-smart-pvc
  namespace: cardano-smart
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: cardano-smart-pv
