apiVersion: v1
kind: Pod
metadata:
  name: upload-pod
  namespace: default
spec:
  containers:
  - name: uploader
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: shared-storage
      mountPath: /mnt/shared
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: private-gpt-pvc
  restartPolicy: Never
