apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-gpt-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-gpt
  template:
    metadata:
      labels:
        app: private-gpt
    spec:
      containers:
      - name: private-gpt
        image: softa/private-gpt-ollama:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PGPT_PROFILES
          value: "docker"
        - name: PGPT_MODE
          value: "ollama"
        resources:
          requests:
            memory: "16Gi"
            cpu: "1800m"
          limits:
            memory: "16Gi"
            cpu: "1800m"
        volumeMounts:
        - name: local-storage
          mountPath: /mnt/shared  # Mounting the local PVC for Qdrant
        - name: shared-storage
          mountPath: /home/worker/app/docs  # Mounting the NFS volume for scraped documents
      volumes:
      - name: local-storage
        persistentVolumeClaim:
          claimName: private-gpt-pvc  # Local PVC for fast access
      - name: shared-storage
        persistentVolumeClaim:
          claimName: filestore-pvc  # NFS-backed PVC for shared storage of scraped documents
